// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSlUoGCCzrbfLO6ifjAE13DGC1plOHNag',
    appId: '1:1020820846496:web:23b0de0a4b8c79df19d6c5',
    messagingSenderId: '1020820846496',
    projectId: 'tiktok-parkjoonseo',
    authDomain: 'tiktok-parkjoonseo.firebaseapp.com',
    storageBucket: 'tiktok-parkjoonseo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBovc6mvLNgNyCASd7Z96m7X1_eY1j9NGo',
    appId: '1:1020820846496:android:659a5012ca54f09f19d6c5',
    messagingSenderId: '1020820846496',
    projectId: 'tiktok-parkjoonseo',
    storageBucket: 'tiktok-parkjoonseo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGCSluPC0P2bJdREbfakqGN8TLtVHEGDE',
    appId: '1:1020820846496:ios:cbc58920afe61de419d6c5',
    messagingSenderId: '1020820846496',
    projectId: 'tiktok-parkjoonseo',
    storageBucket: 'tiktok-parkjoonseo.appspot.com',
    iosClientId: '1020820846496-0rkesp0mtsc1j713ved73ca4k6ffsq49.apps.googleusercontent.com',
    iosBundleId: 'com.joonseo.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGCSluPC0P2bJdREbfakqGN8TLtVHEGDE',
    appId: '1:1020820846496:ios:79f8d2ff93cc2ff719d6c5',
    messagingSenderId: '1020820846496',
    projectId: 'tiktok-parkjoonseo',
    storageBucket: 'tiktok-parkjoonseo.appspot.com',
    iosClientId: '1020820846496-0af49pdoi6dm0nhgokvrdlal87c0dv1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
